name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  typescript-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check Nixpkgs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Enable FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Get npm cache directory
        id: npm-cache-directory
        run: |
          echo "directory=$(nix develop --command npm config get cache | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Set up npm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-directory.outputs.directory }}
          key: update-flake-lock-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            update-flake-lock-npm-cache

      - name: Install npm dependencies
        run: nix develop --command npm ci

      - name: Check formatting
        run: nix develop --command npm run check-fmt

      - name: Lint
        run: nix develop --command npm run lint

      - name: Build
        run: nix develop --command npm run build

      - name: Run test suite
        run: nix develop --command npm run test

      - name: Package
        run: nix develop --command npm run package

      - name: Check git status
        run: git status --porcelain=v1

      - name: Ensure no staged changes
        run: git diff --exit-code
