name: update-flake-lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Enable FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: Update flake.lock
        uses: ./.
        with:
          _internal-strict-mode: true
