name: update-flake-lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  lockfile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - name: Enable FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: Update flake.lock
        uses: ./.
        with:
          _internal-strict-mode: true
